package com.hulusimsek.smartcard.domain.model

import com.hulusimsek.smartcard.core.extension.clearTire

enum class Countries(val code: String, val nativeName: String, val phoneCode: String) {
    AF("AF", "افغانستان", "93"),
    AL("AL", "Shqipëria", "355"),
    DZ("DZ", "الجزائر", "213"),
    AS("AS", "American Samoa", "1-684"),
    AD("AD", "Andorra", "376"),
    AO("AO", "Angola", "244"),
    AI("AI", "Anguilla", "1-264"),
    AQ("AQ", "Antarctica", "672"),
    AG("AG", "Antigua and Barbuda", "1-268"),
    AR("AR", "Argentina", "54"),
    AM("AM", "Հայաստան", "374"),
    AW("AW", "Aruba", "297"),
    AU("AU", "Australia", "61"),
    AT("AT", "Österreich", "43"),
    AZ("AZ", "Azərbaycan", "994"),
    BS("BS", "The Bahamas", "1-242"),
    BH("BH", "البحرين", "973"),
    BD("BD", "বাংলাদেশ", "880"),
    BB("BB", "Barbados", "1-246"),
    BY("BY", "Беларусь", "375"),
    BE("BE", "België", "32"),
    BZ("BZ", "Belize", "501"),
    BJ("BJ", "Bénin", "229"),
    BM("BM", "Bermuda", "1-441"),
    BT("BT", "འབྲུག", "975"),
    BO("BO", "Bolivia", "591"),
    BQ("BQ", "Caribisch Nederland", "599"),
    BA("BA", "Bosna i Hercegovina", "387"),
    BW("BW", "Botswana", "267"),
    BV("BV", "Bouvetøya", "47"),
    BR("BR", "Brasil", "55"),
    IO("IO", "British Indian Ocean Territory", "246"),
    BN("BN", "Brunei Darussalam", "673"),
    BG("BG", "България", "359"),
    BF("BF", "Burkina Faso", "226"),
    BI("BI", "Burundi", "257"),
    CV("CV", "Cabo Verde", "238"),
    KH("KH", "កម្ពុជា", "855"),
    CM("CM", "Cameroun", "237"),
    CA("CA", "Canada", "1"),
    KY("KY", "Cayman Islands", "1-345"),
    CF("CF", "République centrafricaine", "236"),
    TD("TD", "Tchad", "235"),
    CL("CL", "Chile", "56"),
    CN("CN", "中国", "86"),
    CX("CX", "Christmas Island", "61"),
    CC("CC", "Cocos (Keeling) Islands", "61"),
    CO("CO", "Colombia", "57"),
    KM("KM", "جزر القمر", "269"),
    CD("CD", "République démocratique du Congo", "243"),
    CG("CG", "République du Congo", "242"),
    CK("CK", "Cook Islands", "682"),
    CR("CR", "Costa Rica", "506"),
    HR("HR", "Hrvatska", "385"),
    CU("CU", "Cuba", "53"),
    CW("CW", "Curaçao", "599"),
    CY("CY", "Κύπρος", "357"),
    CZ("CZ", "Česká republika", "420"),
    CI("CI", "Côte d'Ivoire", "225"),
    DK("DK", "Danmark", "45"),
    DJ("DJ", "Djibouti", "253"),
    DM("DM", "Dominica", "1-767"),
    DO("DO", "República Dominicana", "1-809"),
    EC("EC", "Ecuador", "593"),
    EG("EG", "مصر", "20"),
    SV("SV", "El Salvador", "503"),
    GQ("GQ", "Guinea Ecuatorial", "240"),
    ER("ER", "ኤርትራ", "291"),
    EE("EE", "Eesti", "372"),
    SZ("SZ", "Eswatini", "268"),
    ET("ET", "ኢትዮጵያ", "251"),
    FK("FK", "Falkland Islands", "500"),
    FO("FO", "Føroyar", "298"),
    FJ("FJ", "Fiji", "679"),
    FI("FI", "Suomi", "358"),
    FR("FR", "France", "33"),
    GF("GF", "Guyane française", "594"),
    PF("PF", "Polynésie française", "689"),
    TF("TF", "Terres australes françaises", "262"),
    GA("GA", "Gabon", "241"),
    GM("GM", "Gambia", "220"),
    GE("GE", "საქართველო", "995"),
    DE("DE", "Deutschland", "49"),
    GH("GH", "Ghana", "233"),
    GI("GI", "Gibraltar", "350"),
    GR("GR", "Ελλάδα", "30"),
    GL("GL", "Kalaallit Nunaat", "299"),
    GD("GD", "Grenada", "1-473"),
    GP("GP", "Guadeloupe", "590"),
    GU("GU", "Guam", "1-671"),
    GT("GT", "Guatemala", "502"),
    GG("GG", "Guernsey", "44"),
    GN("GN", "Guinée", "224"),
    GW("GW", "Guiné-Bissau", "245"),
    GY("GY", "Guyana", "592"),
    HT("HT", "Haïti", "509"),
    HM("HM", "Heard Island and McDonald Islands", "672"),
    VA("VA", "Vaticano", "379"),
    HN("HN", "Honduras", "504"),
    HK("HK", "香港", "852"),
    HU("HU", "Magyarország", "36"),
    IS("IS", "Ísland", "354"),
    IN("IN", "भारत", "91"),
    ID("ID", "Indonesia", "62"),
    IR("IR", "ایران", "98"),
    IQ("IQ", "العراق", "964"),
    IE("IE", "Éire", "353"),
    IM("IM", "Isle of Man", "44"),
    IL("IL", "ישראל", "972"),
    IT("IT", "Italia", "39"),
    JM("JM", "Jamaica", "1-876"),
    JP("JP", "日本", "81"),
    JE("JE", "Jersey", "44"),
    JO("JO", "الأردن", "962"),
    KZ("KZ", "Қазақстан", "7"),
    KE("KE", "Kenya", "254"),
    KI("KI", "Kiribati", "686"),
    KP("KP", "조선민주주의인민공화국", "850"),
    KR("KR", "대한민국", "82"),
    KW("KW", "الكويت", "965"),
    KG("KG", "Кыргызстан", "996"),
    LA("LA", "ສປປລາວ", "856"),
    LV("LV", "Latvija", "371"),
    LB("LB", "لبنان", "961"),
    LS("LS", "Lesotho", "266"),
    LR("LR", "Liberia", "231"),
    LY("LY", "ليبيا", "218"),
    LI("LI", "Liechtenstein", "423"),
    LT("LT", "Lietuva", "370"),
    LU("LU", "Luxembourg", "352"),
    MO("MO", "澳門", "853"),
    MG("MG", "Madagasikara", "261"),
    MW("MW", "Malawi", "265"),
    MY("MY", "Malaysia", "60"),
    MV("MV", "ދިވެހި", "960"),
    ML("ML", "Mali", "223"),
    MT("MT", "Malta", "356"),
    MH("MH", "Marshall Islands", "692"),
    MQ("MQ", "Martinique", "596"),
    MR("MR", "موريتانيا", "222"),
    MU("MU", "Maurice", "230"),
    YT("YT", "Mayotte", "262"),
    MX("MX", "México", "52"),
    FM("FM", "Micronesia", "691"),
    MD("MD", "Moldova", "373"),
    MC("MC", "Monaco", "377"),
    MN("MN", "Монгол улс", "976"),
    ME("ME", "Crna Gora", "382"),
    MS("MS", "Montserrat", "1-664"),
    MA("MA", "المغرب", "212"),
    MZ("MZ", "Moçambique", "258"),
    MM("MM", "မြန်မာ", "95"),
    NA("NA", "Namibia", "264"),
    NR("NR", "Nauru", "674"),
    NP("NP", "नेपाल", "977"),
    NL("NL", "Nederland", "31"),
    NC("NC", "Nouvelle-Calédonie", "687"),
    NZ("NZ", "New Zealand", "64"),
    NI("NI", "Nicaragua", "505"),
    NE("NE", "Niger", "227"),
    NG("NG", "Nigeria", "234"),
    NU("NU", "Niue", "683"),
    NF("NF", "Norfolk Island", "672"),
    MP("MP", "Northern Mariana Islands", "1-670"),
    NO("NO", "Norge", "47"),
    OM("OM", "عمان", "968"),
    PK("PK", "پاکستان", "92"),
    PW("PW", "Palau", "680"),
    PS("PS", "فلسطين", "970"),
    PA("PA", "Panamá", "507"),
    PG("PG", "Papua New Guinea", "675"),
    PY("PY", "Paraguay", "595"),
    PE("PE", "Perú", "51"),
    PH("PH", "Pilipinas", "63"),
    PL("PL", "Polska", "48"),
    PT("PT", "Portugal", "351"),
    PR("PR", "Puerto Rico", "1-787"),
    QA("QA", "قطر", "974"),
    RE("RE", "La Réunion", "262"),
    RO("RO", "România", "40"),
    RU("RU", "Россия", "7"),
    RW("RW", "Rwanda", "250"),
    BL("BL", "Saint-Barthélemy", "590"),
    SH("SH", "Saint Helena", "290"),
    KN("KN", "Saint Kitts and Nevis", "1-869"),
    LC("LC", "Saint Lucia", "1-758"),
    MF("MF", "Saint-Martin", "590"),
    PM("PM", "Saint-Pierre-et-Miquelon", "508"),
    VC("VC", "Saint Vincent and the Grenadines", "1-784"),
    WS("WS", "Samoa", "685"),
    SM("SM", "San Marino", "378"),
    ST("ST", "São Tomé e Príncipe", "239"),
    SA("SA", "المملكة العربية السعودية", "966"),
    SN("SN", "Sénégal", "221"),
    RS("RS", "Srbija", "381"),
    SC("SC", "Seychelles", "248"),
    SL("SL", "Sierra Leone", "232"),
    SG("SG", "Singapore", "65"),
    SX("SX", "Sint Maarten", "1-721"),
    SK("SK", "Slovensko", "421"),
    SI("SI", "Slovenija", "386"),
    SB("SB", "Solomon Islands", "677"),
    SO("SO", "Soomaaliya", "252"),
    ZA("ZA", "South Africa", "27"),
    GS("GS", "South Georgia and the South Sandwich Islands", "500"),
    SS("SS", "South Sudan", "211"),
    ES("ES", "España", "34"),
    LK("LK", "ශ්‍රී ලංකාව", "94"),
    SD("SD", "السودان", "249"),
    SR("SR", "Suriname", "597"),
    SJ("SJ", "Svalbard og Jan Mayen", "47"),
    SE("SE", "Sverige", "46"),
    CH("CH", "Schweiz", "41"),
    SY("SY", "سوريا", "963"),
    TW("TW", "臺灣", "886"),
    TJ("TJ", "Тоҷикистон", "992"),
    TZ("TZ", "Tanzania", "255"),
    TH("TH", "ประเทศไทย", "66"),
    TL("TL", "Timor-Leste", "670"),
    TG("TG", "Togo", "228"),
    TK("TK", "Tokelau", "690"),
    TO("TO", "Tonga", "676"),
    TT("TT", "Trinidad and Tobago", "1-868"),
    TN("TN", "تونس", "216"),
    TR("TR", "Türkiye", "90"),
    TM("TM", "Türkmenistan", "993"),
    TC("TC", "Turks and Caicos Islands", "1-649"),
    TV("TV", "Tuvalu", "688"),
    UG("UG", "Uganda", "256"),
    UA("UA", "Україна", "380"),
    AE("AE", "الإمارات العربية المتحدة", "971"),
    GB("GB", "United Kingdom", "44"),
    US("US", "United States", "1"),
    UY("UY", "Uruguay", "598"),
    UZ("UZ", "O‘zbekiston", "998"),
    VU("VU", "Vanuatu", "678"),
    VE("VE", "Venezuela", "58"),
    VN("VN", "Việt Nam", "84"),
    WF("WF", "Wallis-et-Futuna", "681"),
    EH("EH", "الصحراء الغربية", "212"),
    YE("YE", "اليمن", "967"),
    ZM("ZM", "Zambia", "260"),
    ZW("ZW", "Zimbabwe", "263"),
    UNKNOWN("", "", "");

    companion object {
        fun fromPhoneCode(phoneCode: String?): Countries {
            return entries.find { it.phoneCode.clearTire() == phoneCode?.clearTire() } ?: UNKNOWN
        }

        fun fromCountryCode(code: String?): Countries {
            return entries.find { it.code == code } ?: UNKNOWN
        }
    }
}